# Generated by Django 5.0.1 on 2024-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chanleecrud", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("description", models.TextField(max_length=150)),
            ],
        ),
    ]
